# Generated by Django 3.1.6 on 2021-02-20 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('vw', 'Volkswagen'), ('re', 'Renault'), ('fo', 'Ford'), ('pe', 'Peugeot'), ('mb', 'Mercedes-Benz'), ('bm', 'BMW'), ('op', 'Opel/Vauxhall'), ('sk', 'Skoda'), ('au', 'Audi'), ('to', 'Toyota'), ('ci', 'Citroen'), ('fi', 'Fiat'), ('da', 'Dacia'), ('hy', 'Hyundai'), ('ki', 'Kia'), ('se', 'Seat'), ('ni', 'Nissan'), ('vo', 'Volvo'), ('su', 'Suzuki'), ('ma', 'Mazda'), ('mi', 'Mini'), ('je', 'Jeep'), ('lr', 'Land Rover'), ('mi', 'Mitsubishi'), ('ho', 'Honda')], max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('generation', models.CharField(max_length=64)),
                ('type_of_car', models.CharField(choices=[('su', 'SUV'), ('co', 'coupé'), ('dc', 'dual cowl'), ('fb', 'fastback'), ('hb', 'hatchback'), ('ka', 'kabriolet'), ('ko', 'kombi'), ('lb', 'liftback'), ('li', 'limuzyna'), ('mi', 'mikrovan'), ('mv', 'minivan'), ('pu', 'pick-up'), ('r', 'roadster'), ('s', 'sedan'), ('t', 'targa'), ('v', 'van')], max_length=32)),
                ('fuel', models.CharField(choices=[('be', 'Benzyna'), ('bl', 'Benzyna + LPG'), ('bc', 'Benzyna + CNG'), ('d', 'Diesel'), ('e', 'Elektryczny'), ('et', 'Etanol'), ('h', 'Hybryda'), ('w', 'Wodór')], max_length=32)),
                ('engine', models.IntegerField()),
                ('drive', models.CharField(choices=[('fwd', 'Na przednie koła'), ('rwd', 'Na tylnie koła'), ('awd', 'Na wszystkie koła')], max_length=32)),
                ('look', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('price', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('reliability', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('practicality', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('family_car', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mark', models.CharField(choices=[('vw', 'Volkswagen'), ('re', 'Renault'), ('fo', 'Ford'), ('pe', 'Peugeot'), ('mb', 'Mercedes-Benz'), ('bm', 'BMW'), ('op', 'Opel/Vauxhall'), ('sk', 'Skoda'), ('au', 'Audi'), ('to', 'Toyota'), ('ci', 'Citroen'), ('fi', 'Fiat'), ('da', 'Dacia'), ('hy', 'Hyundai'), ('ki', 'Kia'), ('se', 'Seat'), ('ni', 'Nissan'), ('vo', 'Volvo'), ('su', 'Suzuki'), ('ma', 'Mazda'), ('mi', 'Mini'), ('je', 'Jeep'), ('lr', 'Land Rover'), ('mi', 'Mitsubishi'), ('ho', 'Honda')], max_length=64)),
                ('text', models.CharField(max_length=2048)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_type', models.CharField(choices=[('og', 'Ogłoszenie'), ('sp', 'Sprzedaż'), ('ne', 'News')], max_length=64)),
                ('short_text', models.CharField(max_length=128)),
                ('likes', models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('vw', 'Volkswagen'), ('re', 'Renault'), ('fo', 'Ford'), ('pe', 'Peugeot'), ('mb', 'Mercedes-Benz'), ('bm', 'BMW'), ('op', 'Opel/Vauxhall'), ('sk', 'Skoda'), ('au', 'Audi'), ('to', 'Toyota'), ('ci', 'Citroen'), ('fi', 'Fiat'), ('da', 'Dacia'), ('hy', 'Hyundai'), ('ki', 'Kia'), ('se', 'Seat'), ('ni', 'Nissan'), ('vo', 'Volvo'), ('su', 'Suzuki'), ('ma', 'Mazda'), ('mi', 'Mini'), ('je', 'Jeep'), ('lr', 'Land Rover'), ('mi', 'Mitsubishi'), ('ho', 'Honda')], max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('generation', models.CharField(max_length=64)),
                ('type_of_car', models.CharField(choices=[('su', 'SUV'), ('co', 'coupé'), ('dc', 'dual cowl'), ('fb', 'fastback'), ('hb', 'hatchback'), ('ka', 'kabriolet'), ('ko', 'kombi'), ('lb', 'liftback'), ('li', 'limuzyna'), ('mi', 'mikrovan'), ('mv', 'minivan'), ('pu', 'pick-up'), ('r', 'roadster'), ('s', 'sedan'), ('t', 'targa'), ('v', 'van')], max_length=32)),
                ('fuel', models.CharField(choices=[('be', 'Benzyna'), ('bl', 'Benzyna + LPG'), ('bc', 'Benzyna + CNG'), ('d', 'Diesel'), ('e', 'Elektryczny'), ('et', 'Etanol'), ('h', 'Hybryda'), ('w', 'Wodór')], max_length=32)),
                ('engine', models.IntegerField()),
                ('combustion', models.IntegerField()),
                ('drive', models.CharField(choices=[('fwd', 'Na przednie koła'), ('rwd', 'Na tylnie koła'), ('awd', 'Na wszystkie koła')], max_length=32)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
