# Generated by Django 3.1.6 on 2021-02-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carblog', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
