# Generated by Django 3.1.6 on 2021-02-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carblog', '0003_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
