# Generated by Django 3.1.6 on 2021-02-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carblog', '0004_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
