# Generated by Django 3.1.7 on 2021-02-22 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carblog', '0005_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='model',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='type_of_car',
        ),
        migrations.AddField(
            model_name='rating',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carblog.cars'),
        ),
    ]
