# Generated by Django 3.2.5 on 2021-07-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carblog', '0006_auto_20210223_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='carblog.cars'),
        ),
    ]
